num = int(input('Digite um numero: '))
dobro = (num * 2)
triplo = (num * 3)
raiz = (num**(1/2))
print('O dobro de {} é: {}'.format(num, dobro))
print('O triplo de {} é: {}'.format(num, triplo))
print('A Raiz Quadrada de {} é: {}'.format(num, raiz))
